### ISSUE TITLE
Moderation commands

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/discord-bot-node#65]
- Add a command to add the "warned" role to a user.
  - I should be able to add a reason as a optional parameter
  - I should be able to add the time until the "warned"-role gets automatically removed (default: 2 weeks)
- Add a command to ban a user for a certain time. I should also be able to add a reason.
- Add a command to get information about the rep. This should display a history of past punishments and punishments that are finished (e.g. the warning was automatically removed, or the ban time is over)
- The commands are always used as an answer to a message. The author of the message is the targeted user.

**Comment by Flou21** [comment]
mostly implemented in the other discord bot
banning can be done with yagpdb
